apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkSEp2ZUdGdWJtRTZaMmh3WDBwT01GUlVkbFp4Wm5sVGVIZ3hVMUJTVDBKd1pVMVFUVXB6TUhoVE1qUmFkMm96TXc9PSJ9fX0K
type: kubernetes.io/dockerconfigjson
